name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest anyio httpx pytest-asyncio

      - name: Run tests
        run: |
          python -m pytest -v

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Only deploy if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via Render API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Deploying to Render..."
          curl -X POST "https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Accept: application/json"
          sleep 10  # give it a few seconds to trigger
          curl -X GET "https://api.render.com/services/${RENDER_SERVICE_ID}" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Accept: application/json"